name: Primeira Pipeline

on:
  push:
    branches: [main]
        // - main Também funciona com "-"
         
jobs:
  test_soma:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar Código do Repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'


      - name: Instalar Dependências
        run: npm install

      - name: Executar Testes
        run: npm test soma.js

  test_div:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar Código do Repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'


      - name: Instalar Dependências
        run: npm install

      - name: Executar Testes
        run: npm test soma.js
      
  deploy:
    needs: test_soma, test_div
    runs-on: ubuntu-latest

    steps:
      - run: echo "Deploy realizado"